-- MySQL Script generated by MySQL Workbench
-- Seg 26 Jun 2017 22:04:48 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema newspaper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newspaper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newspaper` DEFAULT CHARACTER SET latin1 ;
USE `newspaper` ;

-- -----------------------------------------------------
-- Table `newspaper`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newspaper`.`categorias` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `newspaper`.`jornalistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newspaper`.`jornalistas` (
  `idJornalista` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `adm` TINYINT(1) NULL,
  `status` TINYINT(1) NULL,
  `tipoUsuario` INT NULL,
  PRIMARY KEY (`idJornalista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newspaper`.`capas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newspaper`.`capas` (
  `idCapa` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `data` LONGBLOB NULL,
  PRIMARY KEY (`idCapa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newspaper`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newspaper`.`noticias` (
  `idNoticia` INT(11) NOT NULL AUTO_INCREMENT,
  `idJornalista` INT(11) NOT NULL,
  `idCategoria` INT(11) NOT NULL,
  `idCapa` INT(11) NOT NULL,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `texto` LONGTEXT NULL DEFAULT NULL,
  `resumo` VARCHAR(255) NULL DEFAULT NULL,
  `dataPublicacao` DATETIME NULL DEFAULT NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`idNoticia`, `idCapa`, `idJornalista`, `idCategoria`),
  INDEX `noticiaTemJornalista_idx` (`idJornalista` ASC),
  INDEX `noticiaTemCapa_idx` (`idCapa` ASC),
  INDEX `noticiaTemCategoria_idx` (`idCategoria` ASC),
  CONSTRAINT `noticiaTemCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `newspaper`.`categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `noticiaTemJornalista`
    FOREIGN KEY (`idJornalista`)
    REFERENCES `newspaper`.`jornalistas` (`idJornalista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `noticiaTemCapa`
    FOREIGN KEY (`idCapa`)
    REFERENCES `newspaper`.`capas` (`idCapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
 
 insert into categorias (descricao) values ("CIÊNCIA"), ("DESASTRES E ACIDENTES"), ("ECONOMIA"), ("EDUCAÇÃO"), ("ESPORTE"), ("NEGÓCIO"), ("POLÍTICA"), ("SAÚDE"), ("TECNOLOGIA"), ("TRANSPORTE");